name: Labeler
on: [pull_request]
jobs:
  label:
    if: "!contains(github.event.head_commit.message, 'Release: v')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: '${{ secrets.GH_TOKEN }}'
