name: Labeler
on: [pull_request]
jobs:
  label:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3.0.2
        with:
          repo-token: '${{ secrets.GH_TOKEN }}'
