name: Lerna publish
on:
  push:
    branches:
      - main
jobs:
  lerna-publish:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node version
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Configure git credentials
        uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          name: 'Miszo Bot'
          email: 'miszo.radomski+gh-bot@gmail.com'
          actor: 'miszo-bot'
          token: '${{ secrets.GH_TOKEN }}'
      - name: Yarn install
        run: yarn
      - name: Publish packages
        run: yarn run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
