name: Lerna publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Authorize .npmrc
        run: npm config set //registry.npmjs.org/:_authToken ${{ env.NODE_AUTH_TOKEN }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Yarn install
        run: yarn
      - name: Publish packages
        run: yarn run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
