name: stylelint-miszo SonarCloud
on:
  release:
    types: [published]
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/stylelint-miszo/**'
jobs:
  sonar-stylelint:
    runs-on: ubuntu-latest
    env:
      PACKAGE_PATH: packages/stylelint-miszo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node version
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ${{ env.PACKAGE_PATH }}
      - name: Create ./reports folder
        run: mkdir -p ./reports
        working-directory: ${{ env.PACKAGE_PATH }}
      - name: Yarn install
        run: yarn
      - name: Audit CI
        run: yarn run audit-ci
        continue-on-error: true
      - name: ESLint
        run: yarn run eslint:json
        working-directory: ${{ env.PACKAGE_PATH }}
        continue-on-error: true
      - name: Prettier
        run: yarn run prettier:check
        working-directory: ${{ env.PACKAGE_PATH }}
        continue-on-error: true
      - name: SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{ env.PACKAGE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version }}
      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ${{ env.PACKAGE_PATH }}/reports
